# Generated by Django 3.2 on 2023-04-30 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_comment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='comment',
        ),
    ]
