# Generated by Django 3.2 on 2023-05-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_comments_comment_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourites',
        ),
    ]
