# Generated by Django 3.2 on 2023-05-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_delete_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
