# Generated by Django 3.2 on 2023-04-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_num_of_raters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='num_of_raters',
            field=models.IntegerField(default=0),
        ),
    ]
